# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('display_name', models.CharField(max_length=100)),
                ('year_of_admission', models.DateField()),
                ('year_of_graduation', models.DateField()),
                ('major_of_studies', models.CharField(max_length=50)),
                ('primary_language', models.CharField(max_length=30)),
                ('secondary_language', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='uploads/resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
