# Generated by Django 2.0.2 on 2018-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major_of_studies',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_language',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_admission',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_graduation',
            field=models.DateField(blank=True),
        ),
    ]
