# Generated by Django 2.0.2 on 2018-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickRegister', '0002_auto_20180219_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major_of_studies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/resume'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_admission',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_graduation',
            field=models.DateField(null=True),
        ),
    ]
