# Generated by Django 2.0.1 on 2018-02-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='name',
        ),
    ]
